"""create user_movie_tracking table

Revision ID: 131551dc6c5c
Revises: 83638c2a82e1
Create Date: 2026-09-26 14:54:49.845248

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '131551dc6c5c'
down_revision: Union[str, Sequence[str], None] = '83638c2a82e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_movie_tracking',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('movie_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('QUERO_ASSISTIR', 'ASSISTINDO', 'ASSISTIDO', 'ABANDONEI', name='moviewatchstatus', native_enum=False, length=30), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['dim_movies.sk_movie_id'], name=op.f('fk_user_movie_tracking_movie_id_dim_movies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_movie_tracking_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_movie_tracking')),
    sa.UniqueConstraint('user_id', 'movie_id', name='uq_user_movie_tracking')
    )
    with op.batch_alter_table('user_movie_tracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_movie_tracking_movie_id'), ['movie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_movie_tracking_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_movie_tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_movie_tracking_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_movie_tracking_movie_id'))

    op.drop_table('user_movie_tracking')
    # ### end Alembic commands ###
