"""add index ix_user_reviews_created_at

Revision ID: 64106a259fad
Revises: b4145534d023
Create Date: 2026-09-27 10:03:34.168225

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '64106a259fad'
down_revision: Union[str, Sequence[str], None] = 'b4145534d023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_reviews_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_reviews_created_at'))

    # ### end Alembic commands ###
