"""create user_reviews table

Revision ID: b4145534d023
Revises: 131551dc6c5c
Create Date: 2026-09-26 23:14:03.501666

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b4145534d023'
down_revision: Union[str, Sequence[str], None] = '131551dc6c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('movie_id', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('has_spoilers', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['dim_movies.sk_movie_id'], name=op.f('fk_user_reviews_movie_id_dim_movies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_reviews_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_reviews')),
    sa.UniqueConstraint('user_id', 'movie_id', name='uq_user_movie_review')
    )
    with op.batch_alter_table('user_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_reviews_movie_id'), ['movie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_reviews_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_reviews_movie_id'))

    op.drop_table('user_reviews')
    # ### end Alembic commands ###
